[project]
name = "expense"
version = "0.1.0"
description = "Project to control my monthly expenses"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=2.3.2",
]
